name: Auto-Update

on:
  push:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  auto-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: Update rank pic
        id: rank-update
        continue-on-error: true
        run: |
          python update.py
      - name: commit
        if: steps.rank-update.outcome == 'success'
        run: |
          git config --global user.email lslyj27761@gmail.com
          git config --global user.name GithubAction
          git add *
          git commit -m "auto update"
      - name: Push changes
        if: steps.rank-update.outcome == 'success'
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}

